FROM python:3.11-slim

RUN pip install --no-cache-dir mlflow

WORKDIR /opt/mlflow

EXPOSE 5050

ENV MLFLOW_TRACKING_URI=file:///shared-data/mlruns

CMD ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5050", "--backend-store-uri", "file:///shared-data/mlruns"]
